- name: Vale Linter
  # You may pin to the exact commit or the version.
  # uses: errata-ai/vale-action@c4213d4de3d5f718b8497bd86161531c78992084
  uses: errata-ai/vale-action@v2.0.1
  with:
    # The Vale CLI version to install.
    version: # optional, default is latest
    # The files to lint: "all" or "<some_folder>".
    files: # optional, default is all
    # Log debugging information to stdout.
    debug: # optional, default is false
    # Reporter of reviewdog command [github-pr-check,github-pr-review,github-check].
    reporter: # optional, default is github-pr-check
    # Exit code for reviewdog when errors are found [true,false]
Default is `false`.

    fail_on_error: # optional, default is false
    # Report level for reviewdog [info,warning,error].
    level: # optional, default is error
    # Filtering for the reviewdog command [added,diff_context,file,nofilter].
Default is added.

    filter_mode: # optional, default is added
    # Space-delimited list of flags for the Vale CLI.
    vale_flags: # optional, default is 
